//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRV_Restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gastos
    {
        public int idGasto { get; set; }
        public int idEmpresa { get; set; }
        public string fechaGastos { get; set; }
        public string responsable { get; set; }
        public string remitente { get; set; }
        public string nombrePersonaRemitente { get; set; }
        public string cedulaPersonaRemitente { get; set; }
        public Nullable<long> valorGasto { get; set; }
        public string descripcionGasto { get; set; }
        public string telefono { get; set; }
        public string ciudad { get; set; }
    }
}
