//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRV_Restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosTemporales
    {
        public int idPedidoTemporal { get; set; }
        public string producto { get; set; }
        public string precio { get; set; }
        public Nullable<int> personalizacion { get; set; }
    }
}
