//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRV_Restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plato
    {
        public int idPlato { get; set; }
        public Nullable<int> idProdcuto { get; set; }
        public Nullable<int> idMenu { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
