//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRV_Restaurante.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProceduresEntities : DbContext
    {
        public ProceduresEntities()
            : base("name=ProceduresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int ActualizarCliente(Nullable<int> idCliente, string p_cliente, string p_direccion, string p_telefono, string p_celular, string p_nota, string p_tipoDocumento, string p_documento)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("idCliente", idCliente) :
                new ObjectParameter("idCliente", typeof(int));
    
            var p_clienteParameter = p_cliente != null ?
                new ObjectParameter("p_cliente", p_cliente) :
                new ObjectParameter("p_cliente", typeof(string));
    
            var p_direccionParameter = p_direccion != null ?
                new ObjectParameter("p_direccion", p_direccion) :
                new ObjectParameter("p_direccion", typeof(string));
    
            var p_telefonoParameter = p_telefono != null ?
                new ObjectParameter("p_telefono", p_telefono) :
                new ObjectParameter("p_telefono", typeof(string));
    
            var p_celularParameter = p_celular != null ?
                new ObjectParameter("p_celular", p_celular) :
                new ObjectParameter("p_celular", typeof(string));
    
            var p_notaParameter = p_nota != null ?
                new ObjectParameter("p_nota", p_nota) :
                new ObjectParameter("p_nota", typeof(string));
    
            var p_tipoDocumentoParameter = p_tipoDocumento != null ?
                new ObjectParameter("p_tipoDocumento", p_tipoDocumento) :
                new ObjectParameter("p_tipoDocumento", typeof(string));
    
            var p_documentoParameter = p_documento != null ?
                new ObjectParameter("p_documento", p_documento) :
                new ObjectParameter("p_documento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarCliente", idClienteParameter, p_clienteParameter, p_direccionParameter, p_telefonoParameter, p_celularParameter, p_notaParameter, p_tipoDocumentoParameter, p_documentoParameter);
        }
    
        public virtual int ActualizarEspecial(Nullable<int> p_idCategoria, Nullable<int> p_idMenu, string p_nombre, Nullable<int> p_precio, string p_preparadoEn, Nullable<bool> p_Activo)
        {
            var p_idCategoriaParameter = p_idCategoria.HasValue ?
                new ObjectParameter("p_idCategoria", p_idCategoria) :
                new ObjectParameter("p_idCategoria", typeof(int));
    
            var p_idMenuParameter = p_idMenu.HasValue ?
                new ObjectParameter("p_idMenu", p_idMenu) :
                new ObjectParameter("p_idMenu", typeof(int));
    
            var p_nombreParameter = p_nombre != null ?
                new ObjectParameter("p_nombre", p_nombre) :
                new ObjectParameter("p_nombre", typeof(string));
    
            var p_precioParameter = p_precio.HasValue ?
                new ObjectParameter("p_precio", p_precio) :
                new ObjectParameter("p_precio", typeof(int));
    
            var p_preparadoEnParameter = p_preparadoEn != null ?
                new ObjectParameter("p_preparadoEn", p_preparadoEn) :
                new ObjectParameter("p_preparadoEn", typeof(string));
    
            var p_ActivoParameter = p_Activo.HasValue ?
                new ObjectParameter("p_Activo", p_Activo) :
                new ObjectParameter("p_Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarEspecial", p_idCategoriaParameter, p_idMenuParameter, p_nombreParameter, p_precioParameter, p_preparadoEnParameter, p_ActivoParameter);
        }
    
        public virtual int ActualizarEstadoPedidoXIdPedido(Nullable<int> idpedido, Nullable<int> estado)
        {
            var idpedidoParameter = idpedido.HasValue ?
                new ObjectParameter("idpedido", idpedido) :
                new ObjectParameter("idpedido", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarEstadoPedidoXIdPedido", idpedidoParameter, estadoParameter);
        }
    
        public virtual int ActualizarPedidoDetalle(Nullable<int> idPedidoDetalle, Nullable<int> idProducto, Nullable<int> idMenu, Nullable<int> estado)
        {
            var idPedidoDetalleParameter = idPedidoDetalle.HasValue ?
                new ObjectParameter("idPedidoDetalle", idPedidoDetalle) :
                new ObjectParameter("idPedidoDetalle", typeof(int));
    
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("idProducto", idProducto) :
                new ObjectParameter("idProducto", typeof(int));
    
            var idMenuParameter = idMenu.HasValue ?
                new ObjectParameter("idMenu", idMenu) :
                new ObjectParameter("idMenu", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarPedidoDetalle", idPedidoDetalleParameter, idProductoParameter, idMenuParameter, estadoParameter);
        }
    
        public virtual int ActualizarProducto(Nullable<int> p_idProducto, Nullable<bool> p_activo, string p_producto, Nullable<int> p_idUnidadMedida, Nullable<int> p_precio, Nullable<int> p_idCategoria, Nullable<int> p_stockMin, string p_preparadoEn)
        {
            var p_idProductoParameter = p_idProducto.HasValue ?
                new ObjectParameter("p_idProducto", p_idProducto) :
                new ObjectParameter("p_idProducto", typeof(int));
    
            var p_activoParameter = p_activo.HasValue ?
                new ObjectParameter("p_activo", p_activo) :
                new ObjectParameter("p_activo", typeof(bool));
    
            var p_productoParameter = p_producto != null ?
                new ObjectParameter("p_producto", p_producto) :
                new ObjectParameter("p_producto", typeof(string));
    
            var p_idUnidadMedidaParameter = p_idUnidadMedida.HasValue ?
                new ObjectParameter("p_idUnidadMedida", p_idUnidadMedida) :
                new ObjectParameter("p_idUnidadMedida", typeof(int));
    
            var p_precioParameter = p_precio.HasValue ?
                new ObjectParameter("p_precio", p_precio) :
                new ObjectParameter("p_precio", typeof(int));
    
            var p_idCategoriaParameter = p_idCategoria.HasValue ?
                new ObjectParameter("p_idCategoria", p_idCategoria) :
                new ObjectParameter("p_idCategoria", typeof(int));
    
            var p_stockMinParameter = p_stockMin.HasValue ?
                new ObjectParameter("p_stockMin", p_stockMin) :
                new ObjectParameter("p_stockMin", typeof(int));
    
            var p_preparadoEnParameter = p_preparadoEn != null ?
                new ObjectParameter("p_preparadoEn", p_preparadoEn) :
                new ObjectParameter("p_preparadoEn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarProducto", p_idProductoParameter, p_activoParameter, p_productoParameter, p_idUnidadMedidaParameter, p_precioParameter, p_idCategoriaParameter, p_stockMinParameter, p_preparadoEnParameter);
        }
    
        public virtual ObjectResult<ConsultarAreas_Result> ConsultarAreas(Nullable<int> p_idrestaurante)
        {
            var p_idrestauranteParameter = p_idrestaurante.HasValue ?
                new ObjectParameter("p_idrestaurante", p_idrestaurante) :
                new ObjectParameter("p_idrestaurante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarAreas_Result>("ConsultarAreas", p_idrestauranteParameter);
        }
    
        public virtual ObjectResult<ConsultarCliente_Result> ConsultarCliente(string p_mode, string p_telefono)
        {
            var p_modeParameter = p_mode != null ?
                new ObjectParameter("p_mode", p_mode) :
                new ObjectParameter("p_mode", typeof(string));
    
            var p_telefonoParameter = p_telefono != null ?
                new ObjectParameter("p_telefono", p_telefono) :
                new ObjectParameter("p_telefono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarCliente_Result>("ConsultarCliente", p_modeParameter, p_telefonoParameter);
        }
    
        public virtual ObjectResult<ConsultarEspecial_Result> ConsultarEspecial(Nullable<int> p_mode, Nullable<int> p_id, string p_nombre, Nullable<int> p_precio)
        {
            var p_modeParameter = p_mode.HasValue ?
                new ObjectParameter("p_mode", p_mode) :
                new ObjectParameter("p_mode", typeof(int));
    
            var p_idParameter = p_id.HasValue ?
                new ObjectParameter("p_id", p_id) :
                new ObjectParameter("p_id", typeof(int));
    
            var p_nombreParameter = p_nombre != null ?
                new ObjectParameter("p_nombre", p_nombre) :
                new ObjectParameter("p_nombre", typeof(string));
    
            var p_precioParameter = p_precio.HasValue ?
                new ObjectParameter("p_precio", p_precio) :
                new ObjectParameter("p_precio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarEspecial_Result>("ConsultarEspecial", p_modeParameter, p_idParameter, p_nombreParameter, p_precioParameter);
        }
    
        public virtual ObjectResult<ConsultarEspecialby_Result> ConsultarEspecialby(Nullable<int> p_mode, Nullable<int> p_id, string p_nombre)
        {
            var p_modeParameter = p_mode.HasValue ?
                new ObjectParameter("p_mode", p_mode) :
                new ObjectParameter("p_mode", typeof(int));
    
            var p_idParameter = p_id.HasValue ?
                new ObjectParameter("p_id", p_id) :
                new ObjectParameter("p_id", typeof(int));
    
            var p_nombreParameter = p_nombre != null ?
                new ObjectParameter("p_nombre", p_nombre) :
                new ObjectParameter("p_nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarEspecialby_Result>("ConsultarEspecialby", p_modeParameter, p_idParameter, p_nombreParameter);
        }
    
        public virtual ObjectResult<ConsultarGuardarEspecial_Result> ConsultarGuardarEspecial(Nullable<int> p_idcategoría, string p_nombre, Nullable<int> p_precio, string p_preparadoEn)
        {
            var p_idcategoríaParameter = p_idcategoría.HasValue ?
                new ObjectParameter("p_idcategoría", p_idcategoría) :
                new ObjectParameter("p_idcategoría", typeof(int));
    
            var p_nombreParameter = p_nombre != null ?
                new ObjectParameter("p_nombre", p_nombre) :
                new ObjectParameter("p_nombre", typeof(string));
    
            var p_precioParameter = p_precio.HasValue ?
                new ObjectParameter("p_precio", p_precio) :
                new ObjectParameter("p_precio", typeof(int));
    
            var p_preparadoEnParameter = p_preparadoEn != null ?
                new ObjectParameter("p_preparadoEn", p_preparadoEn) :
                new ObjectParameter("p_preparadoEn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarGuardarEspecial_Result>("ConsultarGuardarEspecial", p_idcategoríaParameter, p_nombreParameter, p_precioParameter, p_preparadoEnParameter);
        }
    
        public virtual ObjectResult<ConsultarMesas_Result> ConsultarMesas(Nullable<int> p_idarea)
        {
            var p_idareaParameter = p_idarea.HasValue ?
                new ObjectParameter("p_idarea", p_idarea) :
                new ObjectParameter("p_idarea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarMesas_Result>("ConsultarMesas", p_idareaParameter);
        }
    
        public virtual ObjectResult<ConsultarMovimiento_Result> ConsultarMovimiento(string p_mode, Nullable<int> p_mes, Nullable<int> p_idProducto, string p_movimiento, Nullable<System.DateTime> p_fecha, Nullable<System.DateTime> p_fechaFin)
        {
            var p_modeParameter = p_mode != null ?
                new ObjectParameter("p_mode", p_mode) :
                new ObjectParameter("p_mode", typeof(string));
    
            var p_mesParameter = p_mes.HasValue ?
                new ObjectParameter("p_mes", p_mes) :
                new ObjectParameter("p_mes", typeof(int));
    
            var p_idProductoParameter = p_idProducto.HasValue ?
                new ObjectParameter("p_idProducto", p_idProducto) :
                new ObjectParameter("p_idProducto", typeof(int));
    
            var p_movimientoParameter = p_movimiento != null ?
                new ObjectParameter("p_movimiento", p_movimiento) :
                new ObjectParameter("p_movimiento", typeof(string));
    
            var p_fechaParameter = p_fecha.HasValue ?
                new ObjectParameter("p_fecha", p_fecha) :
                new ObjectParameter("p_fecha", typeof(System.DateTime));
    
            var p_fechaFinParameter = p_fechaFin.HasValue ?
                new ObjectParameter("p_fechaFin", p_fechaFin) :
                new ObjectParameter("p_fechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarMovimiento_Result>("ConsultarMovimiento", p_modeParameter, p_mesParameter, p_idProductoParameter, p_movimientoParameter, p_fechaParameter, p_fechaFinParameter);
        }
    
        public virtual ObjectResult<ConsultarPedidoDetalleXidPedido_Result> ConsultarPedidoDetalleXidPedido(Nullable<int> idPedido, string estado)
        {
            var idPedidoParameter = idPedido.HasValue ?
                new ObjectParameter("idPedido", idPedido) :
                new ObjectParameter("idPedido", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarPedidoDetalleXidPedido_Result>("ConsultarPedidoDetalleXidPedido", idPedidoParameter, estadoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ConsultarPedidoDetalleXPedidoEstado(Nullable<int> idPedido, string estado)
        {
            var idPedidoParameter = idPedido.HasValue ?
                new ObjectParameter("idPedido", idPedido) :
                new ObjectParameter("idPedido", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ConsultarPedidoDetalleXPedidoEstado", idPedidoParameter, estadoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ConsultarPedidoXClienteEstado(Nullable<int> idCliente, string estado)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("idCliente", idCliente) :
                new ObjectParameter("idCliente", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ConsultarPedidoXClienteEstado", idClienteParameter, estadoParameter);
        }
    
        public virtual ObjectResult<ConsultarPlato_Result> ConsultarPlato(string p_nombreEspecial, Nullable<int> p_idEspecial)
        {
            var p_nombreEspecialParameter = p_nombreEspecial != null ?
                new ObjectParameter("p_nombreEspecial", p_nombreEspecial) :
                new ObjectParameter("p_nombreEspecial", typeof(string));
    
            var p_idEspecialParameter = p_idEspecial.HasValue ?
                new ObjectParameter("p_idEspecial", p_idEspecial) :
                new ObjectParameter("p_idEspecial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarPlato_Result>("ConsultarPlato", p_nombreEspecialParameter, p_idEspecialParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ConsultarPrecioPedidoTemporal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ConsultarPrecioPedidoTemporal");
        }
    
        public virtual ObjectResult<ConsultarProducto_Result> ConsultarProducto(string p_nombreProducto, Nullable<int> p_idProducto)
        {
            var p_nombreProductoParameter = p_nombreProducto != null ?
                new ObjectParameter("p_nombreProducto", p_nombreProducto) :
                new ObjectParameter("p_nombreProducto", typeof(string));
    
            var p_idProductoParameter = p_idProducto.HasValue ?
                new ObjectParameter("p_idProducto", p_idProducto) :
                new ObjectParameter("p_idProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarProducto_Result>("ConsultarProducto", p_nombreProductoParameter, p_idProductoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Consultarstock(Nullable<short> p_opcion, Nullable<int> p_id)
        {
            var p_opcionParameter = p_opcion.HasValue ?
                new ObjectParameter("p_opcion", p_opcion) :
                new ObjectParameter("p_opcion", typeof(short));
    
            var p_idParameter = p_id.HasValue ?
                new ObjectParameter("p_id", p_id) :
                new ObjectParameter("p_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Consultarstock", p_opcionParameter, p_idParameter);
        }
    
        public virtual ObjectResult<ConsultarUltimoMovimiento_Result> ConsultarUltimoMovimiento(Nullable<short> p_opcion, Nullable<int> p_idProducto)
        {
            var p_opcionParameter = p_opcion.HasValue ?
                new ObjectParameter("p_opcion", p_opcion) :
                new ObjectParameter("p_opcion", typeof(short));
    
            var p_idProductoParameter = p_idProducto.HasValue ?
                new ObjectParameter("p_idProducto", p_idProducto) :
                new ObjectParameter("p_idProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarUltimoMovimiento_Result>("ConsultarUltimoMovimiento", p_opcionParameter, p_idProductoParameter);
        }
    
        public virtual ObjectResult<ConsultarUMedida_Result> ConsultarUMedida(Nullable<int> p_mode, Nullable<int> p_idUMedida, string p_UnidadMedida, Nullable<int> p_idRestaurante)
        {
            var p_modeParameter = p_mode.HasValue ?
                new ObjectParameter("p_mode", p_mode) :
                new ObjectParameter("p_mode", typeof(int));
    
            var p_idUMedidaParameter = p_idUMedida.HasValue ?
                new ObjectParameter("p_idUMedida", p_idUMedida) :
                new ObjectParameter("p_idUMedida", typeof(int));
    
            var p_UnidadMedidaParameter = p_UnidadMedida != null ?
                new ObjectParameter("p_UnidadMedida", p_UnidadMedida) :
                new ObjectParameter("p_UnidadMedida", typeof(string));
    
            var p_idRestauranteParameter = p_idRestaurante.HasValue ?
                new ObjectParameter("p_idRestaurante", p_idRestaurante) :
                new ObjectParameter("p_idRestaurante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarUMedida_Result>("ConsultarUMedida", p_modeParameter, p_idUMedidaParameter, p_UnidadMedidaParameter, p_idRestauranteParameter);
        }
    
        public virtual ObjectResult<ConsultarVariacionesXidPedidoDetalle_Result> ConsultarVariacionesXidPedidoDetalle(Nullable<int> idPedidodetalle)
        {
            var idPedidodetalleParameter = idPedidodetalle.HasValue ?
                new ObjectParameter("idPedidodetalle", idPedidodetalle) :
                new ObjectParameter("idPedidodetalle", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarVariacionesXidPedidoDetalle_Result>("ConsultarVariacionesXidPedidoDetalle", idPedidodetalleParameter);
        }
    
        public virtual int Crear_Usuario(string nombre, string usuario, string password, string activo, Nullable<int> idPerfil, Nullable<int> idRestaurante, Nullable<int> admin)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var activoParameter = activo != null ?
                new ObjectParameter("activo", activo) :
                new ObjectParameter("activo", typeof(string));
    
            var idPerfilParameter = idPerfil.HasValue ?
                new ObjectParameter("idPerfil", idPerfil) :
                new ObjectParameter("idPerfil", typeof(int));
    
            var idRestauranteParameter = idRestaurante.HasValue ?
                new ObjectParameter("idRestaurante", idRestaurante) :
                new ObjectParameter("idRestaurante", typeof(int));
    
            var adminParameter = admin.HasValue ?
                new ObjectParameter("admin", admin) :
                new ObjectParameter("admin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Usuario", nombreParameter, usuarioParameter, passwordParameter, activoParameter, idPerfilParameter, idRestauranteParameter, adminParameter);
        }
    
        public virtual int DeletePedidosTemp(string producto, string precio)
        {
            var productoParameter = producto != null ?
                new ObjectParameter("producto", producto) :
                new ObjectParameter("producto", typeof(string));
    
            var precioParameter = precio != null ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeletePedidosTemp", productoParameter, precioParameter);
        }
    
        public virtual int EliminarPlato(Nullable<int> p_idPlato)
        {
            var p_idPlatoParameter = p_idPlato.HasValue ?
                new ObjectParameter("p_idPlato", p_idPlato) :
                new ObjectParameter("p_idPlato", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarPlato", p_idPlatoParameter);
        }
    
        public virtual int GuardarArea(string area, Nullable<int> idRestaurante)
        {
            var areaParameter = area != null ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(string));
    
            var idRestauranteParameter = idRestaurante.HasValue ?
                new ObjectParameter("idRestaurante", idRestaurante) :
                new ObjectParameter("idRestaurante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarArea", areaParameter, idRestauranteParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GuardarCliente(string p_cliente, string p_direccion, string p_telefono, string p_celular, string p_nota, string p_tipoDocumento, string p_documento)
        {
            var p_clienteParameter = p_cliente != null ?
                new ObjectParameter("p_cliente", p_cliente) :
                new ObjectParameter("p_cliente", typeof(string));
    
            var p_direccionParameter = p_direccion != null ?
                new ObjectParameter("p_direccion", p_direccion) :
                new ObjectParameter("p_direccion", typeof(string));
    
            var p_telefonoParameter = p_telefono != null ?
                new ObjectParameter("p_telefono", p_telefono) :
                new ObjectParameter("p_telefono", typeof(string));
    
            var p_celularParameter = p_celular != null ?
                new ObjectParameter("p_celular", p_celular) :
                new ObjectParameter("p_celular", typeof(string));
    
            var p_notaParameter = p_nota != null ?
                new ObjectParameter("p_nota", p_nota) :
                new ObjectParameter("p_nota", typeof(string));
    
            var p_tipoDocumentoParameter = p_tipoDocumento != null ?
                new ObjectParameter("p_tipoDocumento", p_tipoDocumento) :
                new ObjectParameter("p_tipoDocumento", typeof(string));
    
            var p_documentoParameter = p_documento != null ?
                new ObjectParameter("p_documento", p_documento) :
                new ObjectParameter("p_documento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GuardarCliente", p_clienteParameter, p_direccionParameter, p_telefonoParameter, p_celularParameter, p_notaParameter, p_tipoDocumentoParameter, p_documentoParameter);
        }
    
        public virtual int GuardarEgreso(string ciudad, string remitente, string telefono, string concepto, string direccion, string responsable, string formaPago, string cedula, string valor, Nullable<System.DateTime> fechaEgreso)
        {
            var ciudadParameter = ciudad != null ?
                new ObjectParameter("ciudad", ciudad) :
                new ObjectParameter("ciudad", typeof(string));
    
            var remitenteParameter = remitente != null ?
                new ObjectParameter("remitente", remitente) :
                new ObjectParameter("remitente", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var conceptoParameter = concepto != null ?
                new ObjectParameter("concepto", concepto) :
                new ObjectParameter("concepto", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var responsableParameter = responsable != null ?
                new ObjectParameter("responsable", responsable) :
                new ObjectParameter("responsable", typeof(string));
    
            var formaPagoParameter = formaPago != null ?
                new ObjectParameter("formaPago", formaPago) :
                new ObjectParameter("formaPago", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            var fechaEgresoParameter = fechaEgreso.HasValue ?
                new ObjectParameter("fechaEgreso", fechaEgreso) :
                new ObjectParameter("fechaEgreso", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarEgreso", ciudadParameter, remitenteParameter, telefonoParameter, conceptoParameter, direccionParameter, responsableParameter, formaPagoParameter, cedulaParameter, valorParameter, fechaEgresoParameter);
        }
    
        public virtual int GuardarGasto(Nullable<int> idRestaurante, string fechaGasto, string responsable, string remitente, string nombreRemitente, string cedulaRemitente, Nullable<long> valorGasto, string descripcionGasto, string telefono, string ciudad)
        {
            var idRestauranteParameter = idRestaurante.HasValue ?
                new ObjectParameter("idRestaurante", idRestaurante) :
                new ObjectParameter("idRestaurante", typeof(int));
    
            var fechaGastoParameter = fechaGasto != null ?
                new ObjectParameter("fechaGasto", fechaGasto) :
                new ObjectParameter("fechaGasto", typeof(string));
    
            var responsableParameter = responsable != null ?
                new ObjectParameter("responsable", responsable) :
                new ObjectParameter("responsable", typeof(string));
    
            var remitenteParameter = remitente != null ?
                new ObjectParameter("remitente", remitente) :
                new ObjectParameter("remitente", typeof(string));
    
            var nombreRemitenteParameter = nombreRemitente != null ?
                new ObjectParameter("nombreRemitente", nombreRemitente) :
                new ObjectParameter("nombreRemitente", typeof(string));
    
            var cedulaRemitenteParameter = cedulaRemitente != null ?
                new ObjectParameter("cedulaRemitente", cedulaRemitente) :
                new ObjectParameter("cedulaRemitente", typeof(string));
    
            var valorGastoParameter = valorGasto.HasValue ?
                new ObjectParameter("valorGasto", valorGasto) :
                new ObjectParameter("valorGasto", typeof(long));
    
            var descripcionGastoParameter = descripcionGasto != null ?
                new ObjectParameter("descripcionGasto", descripcionGasto) :
                new ObjectParameter("descripcionGasto", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var ciudadParameter = ciudad != null ?
                new ObjectParameter("ciudad", ciudad) :
                new ObjectParameter("ciudad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarGasto", idRestauranteParameter, fechaGastoParameter, responsableParameter, remitenteParameter, nombreRemitenteParameter, cedulaRemitenteParameter, valorGastoParameter, descripcionGastoParameter, telefonoParameter, ciudadParameter);
        }
    
        public virtual int GuardarIngrediente(string p_ingrediente, Nullable<int> p_idUnidadMedida, Nullable<int> p_precio)
        {
            var p_ingredienteParameter = p_ingrediente != null ?
                new ObjectParameter("p_ingrediente", p_ingrediente) :
                new ObjectParameter("p_ingrediente", typeof(string));
    
            var p_idUnidadMedidaParameter = p_idUnidadMedida.HasValue ?
                new ObjectParameter("p_idUnidadMedida", p_idUnidadMedida) :
                new ObjectParameter("p_idUnidadMedida", typeof(int));
    
            var p_precioParameter = p_precio.HasValue ?
                new ObjectParameter("p_precio", p_precio) :
                new ObjectParameter("p_precio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarIngrediente", p_ingredienteParameter, p_idUnidadMedidaParameter, p_precioParameter);
        }
    
        public virtual int GuardarMesa(string mesa, Nullable<int> idArea)
        {
            var mesaParameter = mesa != null ?
                new ObjectParameter("mesa", mesa) :
                new ObjectParameter("mesa", typeof(string));
    
            var idAreaParameter = idArea.HasValue ?
                new ObjectParameter("idArea", idArea) :
                new ObjectParameter("idArea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarMesa", mesaParameter, idAreaParameter);
        }
    
        public virtual int GuardarMovimiento(Nullable<int> p_idProducto, Nullable<int> idMenu, string p_movimiento, Nullable<int> p_cantidad, Nullable<System.DateTime> p_fecha, Nullable<long> p_precio, string p_observaciones)
        {
            var p_idProductoParameter = p_idProducto.HasValue ?
                new ObjectParameter("p_idProducto", p_idProducto) :
                new ObjectParameter("p_idProducto", typeof(int));
    
            var idMenuParameter = idMenu.HasValue ?
                new ObjectParameter("idMenu", idMenu) :
                new ObjectParameter("idMenu", typeof(int));
    
            var p_movimientoParameter = p_movimiento != null ?
                new ObjectParameter("p_movimiento", p_movimiento) :
                new ObjectParameter("p_movimiento", typeof(string));
    
            var p_cantidadParameter = p_cantidad.HasValue ?
                new ObjectParameter("p_cantidad", p_cantidad) :
                new ObjectParameter("p_cantidad", typeof(int));
    
            var p_fechaParameter = p_fecha.HasValue ?
                new ObjectParameter("p_fecha", p_fecha) :
                new ObjectParameter("p_fecha", typeof(System.DateTime));
    
            var p_precioParameter = p_precio.HasValue ?
                new ObjectParameter("p_precio", p_precio) :
                new ObjectParameter("p_precio", typeof(long));
    
            var p_observacionesParameter = p_observaciones != null ?
                new ObjectParameter("p_observaciones", p_observaciones) :
                new ObjectParameter("p_observaciones", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarMovimiento", p_idProductoParameter, idMenuParameter, p_movimientoParameter, p_cantidadParameter, p_fechaParameter, p_precioParameter, p_observacionesParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GuardarPedido(Nullable<int> idCliente, string pedido, Nullable<int> idMesa, Nullable<int> idUsuario, Nullable<int> estado)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("idCliente", idCliente) :
                new ObjectParameter("idCliente", typeof(int));
    
            var pedidoParameter = pedido != null ?
                new ObjectParameter("pedido", pedido) :
                new ObjectParameter("pedido", typeof(string));
    
            var idMesaParameter = idMesa.HasValue ?
                new ObjectParameter("idMesa", idMesa) :
                new ObjectParameter("idMesa", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GuardarPedido", idClienteParameter, pedidoParameter, idMesaParameter, idUsuarioParameter, estadoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GuardarPedidoDetalle(Nullable<int> idPedido, Nullable<int> idProducto, Nullable<int> idMenu, Nullable<int> estado)
        {
            var idPedidoParameter = idPedido.HasValue ?
                new ObjectParameter("idPedido", idPedido) :
                new ObjectParameter("idPedido", typeof(int));
    
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("idProducto", idProducto) :
                new ObjectParameter("idProducto", typeof(int));
    
            var idMenuParameter = idMenu.HasValue ?
                new ObjectParameter("idMenu", idMenu) :
                new ObjectParameter("idMenu", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GuardarPedidoDetalle", idPedidoParameter, idProductoParameter, idMenuParameter, estadoParameter);
        }
    
        public virtual int GuardarPedidosTemp(string producto, string precio)
        {
            var productoParameter = producto != null ?
                new ObjectParameter("producto", producto) :
                new ObjectParameter("producto", typeof(string));
    
            var precioParameter = precio != null ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarPedidosTemp", productoParameter, precioParameter);
        }
    
        public virtual int GuardarPlato(Nullable<int> p_idProducto, Nullable<int> p_idMenu)
        {
            var p_idProductoParameter = p_idProducto.HasValue ?
                new ObjectParameter("p_idProducto", p_idProducto) :
                new ObjectParameter("p_idProducto", typeof(int));
    
            var p_idMenuParameter = p_idMenu.HasValue ?
                new ObjectParameter("p_idMenu", p_idMenu) :
                new ObjectParameter("p_idMenu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarPlato", p_idProductoParameter, p_idMenuParameter);
        }
    
        public virtual int GuardarUMedida(string p_UnidadMedida, Nullable<int> p_idRestaurante)
        {
            var p_UnidadMedidaParameter = p_UnidadMedida != null ?
                new ObjectParameter("p_UnidadMedida", p_UnidadMedida) :
                new ObjectParameter("p_UnidadMedida", typeof(string));
    
            var p_idRestauranteParameter = p_idRestaurante.HasValue ?
                new ObjectParameter("p_idRestaurante", p_idRestaurante) :
                new ObjectParameter("p_idRestaurante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarUMedida", p_UnidadMedidaParameter, p_idRestauranteParameter);
        }
    
        public virtual int RegistrarProducto(string p_producto, Nullable<int> p_idUnidadMedida, Nullable<int> p_precio, Nullable<int> p_idCategoria, Nullable<int> p_idRestaurante, Nullable<int> p_stockMin, string p_preparadoEn)
        {
            var p_productoParameter = p_producto != null ?
                new ObjectParameter("p_producto", p_producto) :
                new ObjectParameter("p_producto", typeof(string));
    
            var p_idUnidadMedidaParameter = p_idUnidadMedida.HasValue ?
                new ObjectParameter("p_idUnidadMedida", p_idUnidadMedida) :
                new ObjectParameter("p_idUnidadMedida", typeof(int));
    
            var p_precioParameter = p_precio.HasValue ?
                new ObjectParameter("p_precio", p_precio) :
                new ObjectParameter("p_precio", typeof(int));
    
            var p_idCategoriaParameter = p_idCategoria.HasValue ?
                new ObjectParameter("p_idCategoria", p_idCategoria) :
                new ObjectParameter("p_idCategoria", typeof(int));
    
            var p_idRestauranteParameter = p_idRestaurante.HasValue ?
                new ObjectParameter("p_idRestaurante", p_idRestaurante) :
                new ObjectParameter("p_idRestaurante", typeof(int));
    
            var p_stockMinParameter = p_stockMin.HasValue ?
                new ObjectParameter("p_stockMin", p_stockMin) :
                new ObjectParameter("p_stockMin", typeof(int));
    
            var p_preparadoEnParameter = p_preparadoEn != null ?
                new ObjectParameter("p_preparadoEn", p_preparadoEn) :
                new ObjectParameter("p_preparadoEn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegistrarProducto", p_productoParameter, p_idUnidadMedidaParameter, p_precioParameter, p_idCategoriaParameter, p_idRestauranteParameter, p_stockMinParameter, p_preparadoEnParameter);
        }
    
        public virtual ObjectResult<Valida_ingreso_Result> Valida_ingreso(string nombre_usuario, string pass)
        {
            var nombre_usuarioParameter = nombre_usuario != null ?
                new ObjectParameter("nombre_usuario", nombre_usuario) :
                new ObjectParameter("nombre_usuario", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Valida_ingreso_Result>("Valida_ingreso", nombre_usuarioParameter, passParameter);
        }
    }
}
