//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRV_Restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.CompraDetalle = new HashSet<CompraDetalle>();
            this.Inventario = new HashSet<Inventario>();
            this.PedidoDetalle = new HashSet<PedidoDetalle>();
            this.Plato = new HashSet<Plato>();
        }
    
        public int idProdcuto { get; set; }
        public string producto1 { get; set; }
        public Nullable<int> idUnidadMedida { get; set; }
        public Nullable<int> precio { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public Nullable<int> idRestaurante { get; set; }
        public Nullable<bool> activo { get; set; }
        public string preparadoEn { get; set; }
        public Nullable<int> stokMinimo { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompraDetalle> CompraDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoDetalle> PedidoDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plato> Plato { get; set; }
        public virtual Restaurante Restaurante { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
    }
}
