//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRV_Restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variacion
    {
        public int idVariacion { get; set; }
        public Nullable<int> idPedidoDetalle { get; set; }
        public Nullable<int> idVariacionLista { get; set; }
    
        public virtual PedidoDetalle PedidoDetalle { get; set; }
        public virtual VariacionLista VariacionLista { get; set; }
    }
}
